### ISSUE TITLE
problem installing FES2014

### ISSUE THREAD

**Issue by tomatehui** [kvos/CoastSat.slope#10]
Hello Kilian,
I am trying to install the FES2014 model, but when I get to step 6 Open the Anaconda prompt and activate your environment, then run: conda install -c fbriol fes

I get these messages : 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - fes

Current channels:

  - https://conda.anaconda.org/fbriol/win-32
  - https://conda.anaconda.org/fbriol/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

However, I found the fbriol page within Anaconda.org ( https://anaconda.org/fbriol/fes ) with the exact same instruction 

To install this package with conda run:
conda install -c fbriol fes

Still not working.

Do you have any idea of how to override this obstacle?

Thanks in advance.

**Comment by kvos** [comment]
yes try this: `conda install pyfes -c fbriol`

**Comment by tomatehui** [comment]
still not working,  same error as above.

Is there another way ?   or maybe install it manually?

I had no problem earlier this year, but I changed computers.

**Comment by tomatehui** [comment]
problem solved Kilian,  it seems that I did not correctly create the environment initially installing coastsat.

Thanks for the help!
