### ISSUE TITLE
Error SDS_slope

### ISSUE THREAD

**Issue by MaimunaC** [kvos/CoastSat.slope#11]
Hey,

I have problems with the beach slope. When I enter the first command for the initial settings, I get a ModuleNotFoundError: No module named SDS_slope. Does anyone know what the problem could be and how to solve it? I am unfortunately a total beginner in this area

Thanks a lot

**Comment by kvos** [comment]
you need to make sure that when you are running the command to import SDS_slope.py, you are in the same directory as that file. It could be that you are trying to run the command but are not in the right directory so it cannot find it

**Comment by MaimunaC** [comment]
Thank you for youre help
