### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by MaimunaC** [kvos/CoastSat.slope#12]
Hello,
while running the CoastSat code a RunTimeError. So which cause can't be identified. The absolute path in both ini files are correctly set. Down below is the error I get while running the code:

`RuntimeError                              Traceback (most recent call last)
<ipython-input-23-08a8f93774b9> in <module>
      6 config_load =  os.path.join(filepath, 'load_tide.ini')  # change to load_tide.ini
      7 print(config_ocean,config_load)
----> 8 ocean_tide = pyfes.Handler("ocean", "io", config_ocean)
      9 load_tide = pyfes.Handler("radial", "io", config_load)
     10 

RuntimeError: ConfiguRADIAL_2N2__FILE, RADIAL_2N2__LATITUDE, RADIAL_2N2__LONGITUDE, RADIAL_2N2__AMPLITUDE, RADIAL_2N2__PHASE, RADIAL_EPS2__FILE, RADIAL_EPS2__LATITUDE, RADIAL_EPS2__LONGITUDE, RADIAL_EPS2__AMPLITUDE, RADIAL_EPS2__PHASE, RADIAL_J1__FILE, RADIAL_J1__LATITUDE, RADIAL_J1__LONGITUDE, RADIAL_J1__AMPLITUDE, RADIAL_J1__PHASE, RADIAL_K1__FILE, RADIAL_K1__LATITUDE, RADIAL_K1__LONGITUDE, RADIAL_K1__AMPLITUDE, RADIAL_K1__PHASE, RADIAL_K2__FILE, RADIAL_K2__LATITUDE, RADIAL_K2__LONGITUDE, RADIAL_K2__AMPLITUDE, RADIAL_K2__PHASE, RADIAL_L2__FILE, RADIAL_L2__LATITUDE, RADIAL_L2__LONGITUDE, RADIAL_L2__AMPLITUDE, RADIAL_L2__PHASE, RADIAL_LA2__FILE, RADIAL_LA2__LATITUDE, RADIAL_LA2__LONGITUDE, RADIAL_LA2__AMPLITUDE, RADIAL_LA2__PHASE, RADIAL_M2__FILE, RADIAL_M2__LATITUDE, RADIAL_M2__LONGITUDE, RADIAL_M2__AMPLITUDE, RADIAL_M2__PHASE, RADIAL_M3__FILE, RADIAL_M3__LATITUDE, RADIAL_M3__LONGITUDE, RADIAL_M3__AMPLITUDE, RADIAL_M3__PHASE, RADIAL_M4__FILE, RADIAL_M4__LATITUDE, RADIAL_M4__LONGITUDE, RADIAL_M4__AMPLITUDE, RADIAL_M4__PHA`

**Comment by kvos** [comment]
hi @MaimunaC , not sure what this error means. does your ini file looks like this?
![image](https://user-images.githubusercontent.com/7217258/133945475-9f72adc3-21db-41cb-8be7-b2e48b5de85f.png)

**Comment by MaimunaC** [comment]
Thanks for the help. I did not know that the ocean ini. file is called Tide. I first labeled it Radial as well

**Comment by kvos** [comment]
issue solved? please close the issue if you got the model running, thanks
