### ISSUE TITLE
CoastSat Slope Website is Down

### ISSUE THREAD

**Issue by 2320sharon** [kvos/CoastSat.slope#19]
## CoastSat Slope Website is Down
I went to go check out the CoastSat slope website and discovered it was down. Just thought I would give a heads up.
![image](https://user-images.githubusercontent.com/61564689/179798747-a384cbee-2205-4f03-80de-a0dda51cfff8.png)

**Comment by kvos** [comment]
yes unfortunately it's down for the moment, hopefully back online soon!

**Comment by kvos** [comment]
it's back online Sharon!

**Comment by 2320sharon** [comment]
Whohoo! Glad to see its back! 🎊
