### ISSUE TITLE
RuntimeError: No such file or directory ...ocean_tide\mm.nc (even if it is there)

### ISSUE THREAD

**Issue by Julai091** [kvos/CoastSat.slope#2]
Hi Kilian,

I'm trying to run CoastSat.slope code, but i get stucked in ### Option 1: get tide levels from FES2014### 

I get...

 RuntimeError                              Traceback (most recent call last)
<ipython-input-14-32021ffe7345> in <module>
      5 config_ocean = os.path.join(filepath, 'ocean_tide.ini') # change to ocean_tide.ini
      6 config_load =  os.path.join(filepath, 'load_tide.ini')  # change to load_tide.ini
----> 7 ocean_tide = pyfes.Handler("ocean", "io", config_ocean)
      8 load_tide = pyfes.Handler("radial", "io", config_load)
      9 

RuntimeError: No such file or directory : C:\Users\Juliana\anaconda3\CoastSat-master\CoastSat-master\fes\data\fes2014\ocean_tide\ocean_tide\mm.nc

But the file really exists.

Followed the steps...but i must be doing something wrong.

Thank you.

Juliana

**Comment by kvos** [comment]
hi juliana, did you follow all the instructions here https://github.com/kvos/CoastSat.slope/blob/master/doc/FES2014_installation.md? especially step 5 is important!

**Comment by Julai091** [comment]
I did. I'll start all over from the beginning. I'll tell you. Thank you!!

**Comment by Julai091** [comment]
hi kilian...i instaled fes -source  and now it works...thanks.

but now it gives me os not definied.

should i give path to os? 

like...

import os
os.environ["PROJ_LIB"] = "C:/Users/Juliana/anaconda3/envs/coastsat/Library/share"

anyway this is the error

 NameError                                 Traceback (most recent call last)
<ipython-input-1-8f0df71bd144> in <module>
      3 # point to the folder where you downloaded the .nc files
      4 filepath = r'C:/Users/Juliana/anaconda3/CoastSat-master/CoastSat-master/fes-2.9.3-Source/fes-2.9.3-Source/data/fes2014'
----> 5 config_ocean = os.path.join(filepath, 'ocean_tide.ini') # change to ocean_tide.ini
      6 config_load =  os.path.join(filepath, 'load_tide.ini')  # change to load_tide.ini
      7 ocean_tide = pyfes.Handler("ocean", "io", config_ocean)

NameError: name 'os' is not defined

**Comment by Julai091** [comment]
Dead kernel...out of memory.

**Comment by Julai091** [comment]
Hi Kilian,

Do you think that it is possible to use dask in coastsat? i'm trying to run the code but this message shows up when i try to get tide levels from FES2014... 'The kernel appears to have died. It will restart automatically.' , I found out that this erros is given when  i run out of memory. What do you think i should do? Apart from buying another notebook. :)
Thank you

Juliana

**Comment by kvos** [comment]
I don't know I haven't used dask...os is a standard python library, it shouldn't be a problem
