### ISSUE TITLE
fail to install pyfes

### ISSUE THREAD

**Issue by jieAmple** [kvos/CoastSat.slope#21]
Hi Kvos, I follow your instruction till to step6. after I download anaconda, I open 'Anaconda prompt' and type $ conda create -n fes2014 python=3.9. and then type $ conda activate fes2014. I follow typing $ conda install -c fbriol pyfes. the error msg shows as
<img width="660" alt="msg_error" src="https://user-images.githubusercontent.com/114220970/191940602-a7672fe2-4a3f-4bbb-884f-9a1d4408ddd9.PNG">
I also tried to reset the env with different versions of python, still face the similar error. Kindly seek your help
thanks
jie

**Comment by kvos** [comment]
hi jie, I think pyfes is not compatible with python 3.9 yet...I suggest you have 2 environments, one in python 3.7 to run fes2014 and obtain the tide time-series, and then a separate environment with CoastSat.

**Comment by Alerovere** [comment]
Hello all, I get the same error, no matter what my python version is. I tried everything from 2.7 to 3.11.
I opnened an issue on the FES page, but do you have any pointer for me? Probably I am missing something very obvious

**Comment by Alerovere** [comment]
So, the answer was pretty easy, here is the answer from the FES14 issue:
 Try to update your conda environment (conda update --all -c conda-forge) then reinstall the library (conda install pyfes -c fbriol -c conda-forge)

This did the trick. By the way, the latest FES version runs on python 3.9

**Comment by kvos** [comment]
great that it runs on python 3.9 (I still have a separate 3.7 env with pyfes on it). Will update the documentation with Alessio's trick

**Comment by Alerovere** [comment]
I still have to test everything in the same env (python 3.9), but it should work.

**Comment by datpthus** [comment]
@Alerovere thanks for your hint! It works for me.

**Comment by jieAmple** [comment]
dear all, it seems I have installed pyfes, but when I type & import pyfes or & pyfes, it shows the unfound message. Can you give me any hint? I did what Alerovere has shared above to update the env and lib.

(base) C:\Users\HUAWEI>conda activate coastsat

(coastsat) C:\Users\HUAWEI>python
Python 3.9.17 (main, Jul  5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(coastsat) C:\Users\HUAWEI>conda install pyfes -c fbriol
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\HUAWEI\anaconda3\envs\coastsat

  added / updated specs:
    - pyfes


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    curl-8.1.1                 |       h2bbff1b_0         147 KB
    hdf4-4.2.13                |       h712560f_2         1.3 MB
    hdf5-1.12.1                |       h51c971a_3        11.9 MB
    libnetcdf-4.8.1            |       h6685c40_3         668 KB
    libssh2-1.10.0             |       he2ea4bf_2         236 KB
    libzip-1.8.0               |       h289538f_1         131 KB
    mkl-service-2.4.0          |   py39h2bbff1b_1          45 KB
    mkl_fft-1.3.6              |   py39hf11a4ad_1         160 KB
    mkl_random-1.2.2           |   py39hf11a4ad_1         219 KB
    numpy-1.25.0               |   py39h055cbcc_0          13 KB
    numpy-base-1.25.0          |   py39h65a83cf_0         6.2 MB
    pyfes-2.9.4                |   py39h2e52968_0         100 KB  fbriol
    python_abi-3.9             |           2_cp39           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        21.1 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  bzip2              pkgs/main/win-64::bzip2-1.0.8-he774522_0
  curl               pkgs/main/win-64::curl-8.1.1-h2bbff1b_0
  hdf4               pkgs/main/win-64::hdf4-4.2.13-h712560f_2
  hdf5               pkgs/main/win-64::hdf5-1.12.1-h51c971a_3
  icc_rt             pkgs/main/win-64::icc_rt-2022.1.0-h6049295_2
  intel-openmp       pkgs/main/win-64::intel-openmp-2023.1.0-h59b6b97_46319
  jpeg               pkgs/main/win-64::jpeg-9e-h2bbff1b_1
  libcurl            pkgs/main/win-64::libcurl-8.1.1-h86230a5_0
  libnetcdf          pkgs/main/win-64::libnetcdf-4.8.1-h6685c40_3
  libssh2            pkgs/main/win-64::libssh2-1.10.0-he2ea4bf_2
  libzip             pkgs/main/win-64::libzip-1.8.0-h289538f_1
  lz4-c              pkgs/main/win-64::lz4-c-1.9.4-h2bbff1b_0
  mkl                pkgs/main/win-64::mkl-2023.1.0-h8bd8f75_46356
  mkl-service        pkgs/main/win-64::mkl-service-2.4.0-py39h2bbff1b_1
  mkl_fft            pkgs/main/win-64::mkl_fft-1.3.6-py39hf11a4ad_1
  mkl_random         pkgs/main/win-64::mkl_random-1.2.2-py39hf11a4ad_1
  numpy              pkgs/main/win-64::numpy-1.25.0-py39h055cbcc_0
  numpy-base         pkgs/main/win-64::numpy-base-1.25.0-py39h65a83cf_0
  pyfes              fbriol/win-64::pyfes-2.9.4-py39h2e52968_0
  python_abi         conda-forge/win-64::python_abi-3.9-2_cp39
  tbb                pkgs/main/win-64::tbb-2021.8.0-h59b6b97_0
  xz                 pkgs/main/win-64::xz-5.4.2-h8cc25b3_0
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_0
  zstd               pkgs/main/win-64::zstd-1.5.5-hd43e919_0


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(coastsat) C:\Users\HUAWEI>python
Python 3.9.17 (main, Jul  5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(coastsat) C:\Users\HUAWEI>import pyfes
'import' is not recognized as an internal or external command,
operable program or batch file.

(coastsat) C:\Users\HUAWEI>pyfes
'pyfes' is not recognized as an internal or external command,
operable program or batch file.

(coastsat) C:\Users\HUAWEI>conda deactivate

(base) C:\Users\HUAWEI>conda activate coastsat

(coastsat) C:\Users\HUAWEI>import pyfes
'import' is not recognized as an internal or external command,
operable program or batch file.

(coastsat) C:\Users\HUAWEI>pyfes
'pyfes' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jorge-necochea** [comment]
I have the same problem with the instalation:
(coastsatslope) C:\Users\Jorge>conda install -c fbriol pyfes
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyfes -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=3.5

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

Please help me.

**Comment by kvos** [comment]
sorry I thought this was resolved.
