### ISSUE TITLE
error in estimating beach-face slopes along the transect, (ValueError: zero-size array to reduction operation maximum which has no identity)

### ISSUE THREAD

**Issue by juni666666** [kvos/CoastSat.slope#23]
My Data's Date range is = ['1980-01-01', '2000-12-31']
ROI is (Karachi coast) = [[[67.00833391012465,24.78819451085644],
              [67.05107759298598,24.78819451085644],
              [67.05107759298598,24.81250397390977],
              [67.00833391012465,24.81250397390977],
              [67.00833391012465,24.78819451085644]]]
sat_list = ['L5' , 'L7']
I have used all this info to gather the .pkl, transects.geojson and the .output files needed for coastsat.slope module
i am having the error in estimating beach-face slopes along the transect as ' SDS_slope.plot_spectrum_all(dates,composite,tsall,settings_slope, title) ' and further errors related to this

![Uploading kvosq.jpg…]()

**Comment by kvos** [comment]
you need to consider the date range  2000-now as this is when 2 satellites are in orbit simultaneously
