### ISSUE TITLE
Issues downloading load_tide.tar.xz and ocean_tide.tar.xz from aviso website

### ISSUE THREAD

**Issue by Fanikiso** [kvos/CoastSat.slope#24]
Hello all,
I am currently attempting to download the above mentioned auxiliary files as per FES2014 installation instructions (https://github.com/kvos/CoastSat.slope/blob/master/doc/FES2014_installation.md), however, I am having trouble actually downloading them. They seem to be approximately 1.3GB and my downloads seem to be failing. I am accessing them through the TDS access service on aviso. The FTP seems to be unresponsive and I am downloading on google chrome. I have been trying for days to no avail. Any advice? What am I missing?

<img width="957" alt="Screenshot_20221231_142304" src="https://user-images.githubusercontent.com/95992987/210136624-ea60c5f5-8f37-45fd-be9c-1230a72f29ce.png">

<img width="656" alt="Screenshot_20221231_141325" src="https://user-images.githubusercontent.com/95992987/210136363-13cef06a-71d1-4a23-b84c-db0841d5d062.png">

**Comment by ddbuscombe** [comment]
I just did this with CyberDuck and found it straightforward. I logged in with my username and password, then selected the following file

![ftp-tides](https://user-images.githubusercontent.com/3596509/222540544-5c2dc282-1908-48b7-aa4c-afb5b022d4a5.PNG)

**Comment by ddbuscombe** [comment]
However, the 'ini' files mentioned [here](https://github.com/kvos/CoastSat.slope/blob/19036237299127338ac3f1f622729780035407bd//doc/FES2014_installation.md) are missing - see https://github.com/kvos/CoastSat.slope/issues/25

The file 'ocean_tide' is also missing. Is this needed?

**Comment by kvos** [comment]
this was resolved.
