### ISSUE TITLE
Incorrect slope estimate

### ISSUE THREAD

**Issue by mkewsds12** [kvos/CoastSat.slope#27]
Hi @kvos, it is a very nice job. I have some questions for you. Why is my estimated slope all one value (set maximum value)? Sometimes it calculates the correct value, sometimes it doesn't. This confuses me very much. I only extract one shoreline each year for analysis.

**Comment by kvos** [comment]
You need to use ALL the shorelines to have enough data to get an estimate of the beach-face slope. With one shoreline per year it will not be enough data to capture the tidal signal in the shoreline time-series.

**Comment by mkewsds12** [comment]
Thanks for your answer, the problem has been solved！
