### ISSUE TITLE
How to install Coastsat.slope and FES2014

### ISSUE THREAD

**Issue by jobthoma97** [kvos/CoastSat.slope#29]
Hello 

I have installed coastsat and been using it. Then for Tidal correction, I was trying to install Coastsat.slope but was not able to figure out the steps. Can someone please help with the steps for installing Coastat.slope and FES2014.

**Comment by jelroig** [comment]
Hi @jobthoma97 

For the CoastSat.slope, you just have to download the setup and extract it to your CoastSat folder, that's all.

Regarding FES2014, I had a few challenges with the installation, so I am currently trying to use a different tide model.

**Comment by jobthoma97** [comment]
> Hi @jobthoma97
> 
> For the CoastSat.slope, you just have to download the setup and extract it to your CoastSat folder, that's all.
> 
> Regarding FES2014, I had a few challenges with the installation, so I am currently trying to use a different tide model.

Oh. I see.
Thankyou for the solution.

What I did was, created a new environment in conda for CoastSat.Slope in  a new directory and was trying to use the new conda environment of CoastSat.Slope and Coastsat differently.

I'll try using the above mentioned suggestion. 

Thank you once again  @jelroig

**Comment by jelroig** [comment]
@jobthoma97 You're welcome, I hope it's working now!
