### ISSUE TITLE
 Saving .csv tide file

### ISSUE THREAD

**Issue by pgurruchaga** [kvos/CoastSat.slope#3]
Hi! I've been using CoastSat and now I'm trying to improve my results with tidal correction, so now I'm using the results given by coastsat slope. The thing is, it doesn't seem to save the .csv file obtained by FES 2014, wich I need as an input at coastsat in tidal correction section.  So the question is, how could I edit the coastsat slope code so it saves the .csv file of tide data from FES?

Thanks a lot, 
Paula.

**Comment by kvos** [comment]
hi @pgurruchaga, you can put the time-series from FES2014 into a pandas dataframe and then export to csv , here is an example https://towardsdatascience.com/how-to-export-pandas-dataframe-to-csv-2038e43d9c03

**Comment by pgurruchaga** [comment]
Solved, thanks Kilian
