### ISSUE TITLE
Error in slope estimation settings while using CoastSat.slope

### ISSUE THREAD

**Issue by jobthoma97** [kvos/CoastSat.slope#31]
While running the code of **CoastSat.slope**, I reiceved an error of "boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 3".

The dates for the shoreline in **Coastsat** is from '2020-01-01' to  '2020-02-28', and I have used 3 shorelines of date 2020-01-16, 2020-02-01 and 2020-02-17.
These 3 shoreline were delineated from Landsat 8.

In the error they have highlighted "Cross_distance" is it something related to transect.

Does anyone have any solutions why this error is occurring ! 

@kvos I have also attached the screenshot of the error.
![error](https://github.com/kvos/CoastSat.slope/assets/85024689/2c507f3f-45c9-4656-8614-7544a63dc4ba)

**Comment by kvos** [comment]
hi @jobthoma97 , 3 shorelines will not be enough, you need at least 20 years of shoreline to estimate the slope. All the best

**Comment by jobthoma97** [comment]
> hi @jobthoma97 , 3 shorelines will not be enough, you need at least 20 years of shoreline to estimate the slope. All the best

@kvos Thank you for replying but may I know what is the reason for using at least 20 years of shoreline to estimate slope. For calculating slope, we just need the min and max elevation and the distance between 2 elevation points.

Is there any way I can change the number of shoreline as per my requirements.
