### ISSUE TITLE
ModuleNotFoundError: No module named 'SDS_slope'

### ISSUE THREAD

**Issue by KeilorCordero** [kvos/CoastSat.slope#37]
Hi,

Im working with this great methodology to research beach change and erosion in a National Park in Costa Rica. 

When importing SDS_slope from coastsat, it keeps returning the same error:

### #CoastSat.slope:

```
#initial settings
%reload_ext autoreload
%autoreload 2
import os
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import pytz
import pickle
 beach slope estmation module
import SDS_slope
```

### This is the error that I keep getting

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[64], line 13
     11 import pickle
     12 # beach slope estmation module
---> 13 import SDS_slope

ModuleNotFoundError: No module named 'SDS_slope'

```

### I have also tryed:

`from coastsat import SDS_slope`

but i did not work either

Maybe there is an issue with the coastsat package when it was updated. I would appreciate all your help  @kvos 

Thank you for your time.

**Comment by kvos** [comment]
make sure that the working directory of your notebook is where SDS_slope.py is located (same folder). Then you don't need from coastsat import, just import SDS_slope.
