### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by Julai091** [kvos/CoastSat.slope#4]
Hi Kilian,

I'm getting this issue while running **Option 1: get tide levels from FES2014**
I must be doing something wrong with FES2014 data.

Got this message:

ValueError                                Traceback (most recent call last)
<ipython-input-6-d7c96207e5a7> in <module>
     15 dates_fes, tide_fes = SDS_slope.compute_tide(coords,settings_slope['date_range'],time_step,ocean_tide,load_tide)
     16 # get tide level at time of image acquisition
---> 17 tide_sat = SDS_slope.compute_tide_dates(coords, dates_sat, ocean_tide, load_tide)
     18 
     19 # plot tide time-series

~\anaconda3\CoastSat\CoastSat.slope\SDS_slope.py in compute_tide_dates(coords, dates, ocean_tide, load_tide)
    482     lats = coords[1]*np.ones(len(dates))
    483     # compute heights for ocean tide and loadings
--> 484     ocean_short, ocean_long, min_points = ocean_tide.calculate(lons, lats, dates_np)
    485     load_short, load_long, min_points = load_tide.calculate(lons, lats, dates_np)
    486     # sum up all components and convert from cm to m

ValueError: Incompatible arguments:
 1. calculate(self, numpy.ndarray[m, 1], numpy.ndarray[m, 1], numpy.ndarray[datetime.datetime[m, 1]])
 2. calculate(self, numpy.ndarray[m, 1], numpy.ndarray[m, 1], numpy.ndarray[datetime64[us][m, 1]])

Thank you!

Juliana

**Comment by Julai091** [comment]
Hi...
I started all over again and again...carefully doing all the steps with FES, but i get the same error again. Any idea?

Thank you

Juliana

**Comment by Julai091** [comment]
Hi again, :)
When i try to plot  shorelines and transects this shows up, only transects with no shorelines, even though it is plotted in Coastsat.
![download (1)](https://user-images.githubusercontent.com/49702201/104962771-e91fe180-59b7-11eb-981d-e124f67ee0ae.png)
![Figure_1-8](https://user-images.githubusercontent.com/49702201/104963005-664b5680-59b8-11eb-846c-69b829051409.png)

Could it be the output.pkl that is not 'working'?

**Comment by Julai091** [comment]
Only Landsat. Ooops

But still getting 
ValueError: Incompatible arguments:
 1. calculate(self, numpy.ndarray[m, 1], numpy.ndarray[m, 1], numpy.ndarray[datetime.datetime[m, 1]])
 2. calculate(self, numpy.ndarray[m, 1], numpy.ndarray[m, 1], numpy.ndarray[datetime64[us][m, 1]])

**Comment by kvos** [comment]
hi julia, I am happy to help you but could you please describe the issue with some more details? could you solve the FES2014 problem? Are your shorelines and transects in the same coordinate system?

**Comment by Julai091** [comment]
Hi Kilian...I reinstalled Anaconda and everything works perfect now...Thank you.

The only thing is that tide is underestimated...trying to figure it out. My region has tides up to 5 m.  

But it shows up to 2m.

![tides](https://user-images.githubusercontent.com/49702201/105615758-c6277000-5db1-11eb-8c3d-a8a97fc6b3c5.png)

Thank you!!!

**Comment by kvos** [comment]
cool! that looks like a 5m tidal range to me...you can check the model output at a different grid point, and also I noticed is better to give it a point that is 5-10km offshore as the resolution of the tide model is about 7km. I think however that's more a question for FES2014, who develop and maintain the tide model

**Comment by Julai091** [comment]
Thank you so much Kilian!!!
