### ISSUE TITLE
load_tide. ini and ocean_tide. ini files 

### ISSUE THREAD

**Issue by tomatehui** [kvos/CoastSat.slope#5]
Hello Kilian,
I just downloaded the load_tide and ocean_tide which contain the 34 files, however, in your example there are two files (load_tide.ini and ocean_tide.ini) 
My question is: where these two files downloaded from the Aviso FTP ( I could not find them)  or did you made them this using the info provided in the image?

best regards

Tona

**Comment by kvos** [comment]
hi @tomatehui , you are right those files don't come from the Aviso FTP, they come from the bitbucket fes2014 repo.
When you do step 1 and download the fes repo from bitbucket, there is a /data folder, those files are in there.
 If you can't find them you can download them again from here: https://bitbucket.org/cnes_aviso/fes/src/master/data/fes2014/. 
I'll update the documentation somehow to make it more clear, thanks for reporting this.

**Comment by tomatehui** [comment]
Thank you for the prompt response.  I will continue exploring this quite amazing and useful tool. 

regards
Tona.
