### ISSUE TITLE
.ini files not found

### ISSUE THREAD

**Issue by Surfix** [kvos/CoastSat.slope#7]
Thank you for your work on shoreline monitoring. I have been following the coastsat notebook. I need to do tidal correction, so I want to use the fes2014 tide model using this CoastSat.slope repository. After downloading and extracting load_tide and ocean_tide files, I can't find the .ini files in the folder.  See the content of my directory in the image below. Your guide is highly appreciated. Thanks

![image](https://user-images.githubusercontent.com/51313944/111295449-571a1980-8686-11eb-952a-def073c1c04e.png)

**Comment by kvos** [comment]
hi @Surfix , did you download the package from Bitbucket at https://bitbucket.org/fbriol/fes/downloads/? the .ini files should be in there, I suggest you copy your downloaded files into the same structure as in the instructions: fes-2.9.1-Source/data/fes2014. let me know how you go

**Comment by Surfix** [comment]
Hi @kvos , thank you for the guide. To download the files, I followed the instruction you provided [here](https://github.com/kvos/CoastSat.slope/blob/master/doc/FES2014_installation.md). I also just checked the bitbucket but the required .ini files are not in any of the folders. Thanks for helping.

**Comment by kvos** [comment]
https://bitbucket.org/cnes_aviso/fes/src/master/data/fes2014/

**Comment by Surfix** [comment]
I have been able to estimate beach slope from the satellite derived shorelines. Thank you for your guide.

For the tidal correction in your example notebook, the timeseries of tide level was in csv format. For my own notebook, the tide level data from fes2014 model is in numpy. There is also a dates_sat variable with corresponding length as the tide level data which I believe correspond to the date of the tide level. How do I format this in csv format like you have it in the NARRA_tides.csv file. 
![image](https://user-images.githubusercontent.com/51313944/111458647-a3cc2600-8754-11eb-9a65-4f5424ad4092.png)

Also we remove the 'S2' satellites for beach slope calculation which I understand the rational. Do I need to do this if I am to get the tide level time series for the tidal correction?. Some of the satellite derived shorelines were extracted from 'S2'.
 

I am so grateful for your help. Thanks

**Comment by kvos** [comment]
good job on estimating the slopes. For tidal correction you will need the tide level associated with each image and the slope estimate. Since you have Coastsat.slope running, you can use this call tides_sat = `SDS_slope.compute_tide_dates(coords,output['dates'],ocean_tide,load_tide)` to get the tide levels at the time of image acquisition from the fes2014 model. You will just need this numpy array for the tidal correction and can go directly to cell 19 (no need to read a csv and look for the tide levels closest to each image timestamp).

**Comment by Surfix** [comment]
Thank you so much. I am very grateful for your guidance.
