### ISSUE TITLE
find tidal peak frequency error

### ISSUE THREAD

**Issue by NO645** [kvos/CoastSat.slope#8]
This line in coastsat.slope keeps returning an error:
`  settings_slope['freqs_max'] = SDS_slope.find_tide_peak(dates_sat,tide_sat,settings_slope)`

```
  File "C:\Users\RDCHLNRO\AppData\Local\Continuum\anaconda3\envs\coastsat3152021\lib\site-packages\coastsat\SDS_slope.py", line 506, in find_tide_peak
    idx_max = idx_peaks[freqs[idx_peaks] > settings['freqs_cutoff']][0]

IndexError: index 0 is out of bounds for axis 0 with size 0
```

These are the variables being sent to the function:
```
([datetime.datetime(2018, 6, 8, 15, 32, 54, tzinfo=<UTC>),
  datetime.datetime(2018, 6, 15, 15, 39, 9, tzinfo=<UTC>),
  datetime.datetime(2018, 6, 24, 15, 33, 4, tzinfo=<UTC>),
  datetime.datetime(2018, 7, 1, 15, 39, 19, tzinfo=<UTC>),
  datetime.datetime(2018, 7, 10, 15, 33, 13, tzinfo=<UTC>),
  datetime.datetime(2018, 7, 17, 15, 39, 27, tzinfo=<UTC>)],
 array([0.367, 0.358, 0.363, 0.358, 0.363, 0.358]),
 {'slope_min': 0.035,
  'slope_max': 0.2,
  'delta_slope': 0.005,
  'date_range': [datetime.datetime(2018, 6, 1, 0, 0, tzinfo=<UTC>),
   datetime.datetime(2018, 8, 1, 0, 0, tzinfo=<UTC>)],
  'n_days': 8,
  'n0': 50,
  'freqs_cutoff': 3.8580246913580245e-07,
  'delta_f': 1e-08})
```

Maybe there is an issue with the small amount of data being sent? That was not an issue for me previously, but I recently updated all of the coastsat code.

Thank you for your time.

**Comment by kvos** [comment]
yes not enough data points, you need to use the entire Landsat archive as in the example, otherwise it cannot resolve the spring/neap cycles and find the frequency of the tidal signal

**Comment by NO645** [comment]
Does that mean we can't get coastsat slope estimates without using ~20 years of data?

`# clip the dates between 1999 and 2020 as we need at least 2 Landsat satellites 
`
Is there a smaller range that's still suitable?

I looked at the old version I had of coastsat.slope (~6/2020) and saw that the date range given then was 2017 to 2018. Would results from those runs now be considered invalid? I'm sorry, I'm just unsure what has changed about the technique that requires the large expansion of the data. If there's some prior writing on the topic feel free to point me that way so you don't have to re-iterate it all here.

Thank you!

**Comment by kvos** [comment]
yes you need 20 years of data when using Landsat. See this paper https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020GL088365, if you don't have access there is an open-access preprint as well https://www.essoar.org/doi/10.1002/essoar.10502903.1.
You could get away with less than 20 years if you include more satellites, like S2, PlanetLabs etc... but only the Landsat-only method has been validated.

**Comment by NO645** [comment]
Hi, I was hoping I could inquire a bit more about the relationship between the time span and the slope calculation. I can see in the paper that 20 years of data was used for your calculations at the test sites, but it's not clear to me what effect that time span had on the confidence in the resulting slopes. I also wasn't able to tell what effect the addition of the Sentinel-2 imagery would have on the required time span for a successful calculation.

In testing I've found that coastsat.slope will come up with a value for the beach slope given much shorter time spans than 20 years using only landsat data. If the calculation succeeds at finding a slope that minimizes that peak tidal frequency band for shorter time periods can those results be considered usable? This is within the context of a larger coastsat workflow in which a user has limited data to valid imagery in a prior step, not in the automated methodology described by the paper which seemed to use the cloud cover as a substitute to manual image selection.

Thank you again for your input and time.

**Comment by kvos** [comment]
hi @NO645 , sorry I completely missed that you reopened this issue (sometimes better to tag me @kvos if I don't see it).
you are right the slope estimation may work with shorter timespans too. I just haven't experimented to see what is the "minimum" timespan, and I am sure that this minimum timespan will depend on the tidal range and slope itself (which define the horizontal extent of the tidal excursion). To see if you are getting valid estimates you can look at the spectrum and the energy curve that are plotted by the toolbox, you will have more confidence in the estimate if the minimum on the energy curve is well defined (currently working on including confidence bands for the estimates based on this).
